### ISSUE TITLE
Better support for Section[5]/strings/vtables

### ISSUE THREAD

**Issue by TheGag96** [Sammi-Husky/reltools#1]
BrawlBox/BrawlCrate has support for all the vtable stuff that goes in Section[5]. Right now, it's just treated like raw words with some relocations in there. Somehow, it would be nice if the class and function name strings were actually parsed and easier to see / search through / edit. (Granted, I don't know very well how these really work or how they're supposed to be used in the first place lol.)

**Comment by Sammi-Husky** [comment]
The vtables are just that, actually. They are arrays of relocations to functions. There are no function name strings, only the name of the class the vtable belongs to. The data that is actually at those addresses in `Section[5]` is empty and the only way we know what the function names are is due to the map files on the korean brawl disc.

I am probably going to be disassembling the string names for the classes though. It reduces the size of the resulting text file by a lot, and they are part of the custom [Runtime Type Information](https://docs.microsoft.com/en-us/cpp/cpp/run-time-type-information) format that the CodeWarrior compiler generates. They are useful for identifying what class each vtable belongs to.

**Comment by TheGag96** [comment]
Sorry, right - the strings are just class names, not function names. I have seen them being used to make `dynamic_cast` work. Being able to add new entries seems like it's necessary for properly porting some functions from a module to another.

**Comment by Sammi-Husky** [comment]
The tool uses gnu `as` under the hood so if you port anything over and use `.asciz` or `.string` it will assemble correctly. Editing a vtable entry should be just editing the relocation tag at the end of the line to point to the symbol for the function you want to point to. Similarly, adding a new entry to the vtable would just be adding a `.4byte 0x00000000` line and relocation tag.

Hopefully in the near future I'll be adding some checks to disassemble ascii data automatically. This way it won't need to be done manually anymore.

Aside from disassembling the strings properly, any abstraction layer or syntax on top of the vtable structure would be outside the scope of the tool. Most games have RTTI disabled and don't follow Brawl's conventions anyways, so it would become game specific code. 

This does, however, give me some neat ideas about a VS Code extension for working with the output of this tool. Perhaps one which adds tooltips, auto-complete, navigation, and _**code snippets**_ for easily creating CodeWarrior vtables.

**Comment by Sammi-Husky** [comment]
Support for auto-disassembly of strings was added in 19fe75d3994ccddc86535406446abefab219699f. 

Note that there is still the chance of false positives in this, but they should fairly unlikely. I've only run into it on custom rels like `bx_fighter.rel` for the BrawlEx. Even in the case of a false positive, the data should still compile and match even if it's represented as string in the source.
