### ISSUE TITLE
Disabling Stage Hazards of Spear Pillar by editing .rel

### ISSUE THREAD

**Issue by Lilothestitch16** [Sammi-Husky/reltools#2]
Is it possible to edit Spear Pillar's rel and turn off the hazards by having the Pokémon show up and then leaving after? If so, how can I do this with the .rel tool?

**Comment by Sammi-Husky** [comment]
Yes, that is 100% possible to do with the tool and a good use for it. As for how to approach the issue and go about doing it, that's something you'll have to figure out on your own. You'll have to Reverse Engineer how the hazards work in the rel by reading through the code and disable it by removing or `nop`'ing the calls out. 

I would ask in the Custom Brawl Modding discord server. There are a lot of helpful folks there (myself included) who would be willing to take a look at it for you.

Also, in the future please refrain from using the GitHub issues for questions like this. They should be used for feature requests, bug reports, and questions relating to the tool itself rather than how to use it to accomplish something specific in a specific game :)

**Comment by Lilothestitch16** [comment]
I'm not good with Reverse Engineering and I tried to ask in Custom Brawl Modding Discord Sever but I didn't get much help.
